import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import jsxA11y from "eslint-plugin-jsx-a11y";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "playwright-report",
      "test-results",
      "e2e",
      "playwright.config.ts",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        project: ["./tsconfig.json", "./tsconfig.node.json"],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { react, "react-hooks": reactHooks, "jsx-a11y": jsxA11y },
    // Pinned rather than "detect": eslint-plugin-react's version sniffing
    // calls `context.getFilename()`, which ESLint 10 removed.
    settings: { react: { version: "19.2" } },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": "error",
      // New in eslint-plugin-react-hooks 7 (React Compiler ruleset). It flags
      // the "reset local state when a dialog opens" effect used across the
      // feature dialogs. Migrating those to remount-by-key is a behavioural
      // refactor, so it is tracked separately rather than done alongside a
      // dependency bump.
      "react-hooks/set-state-in-effect": "off",
    },
  },
  {
    // Vendored shadcn/ui primitives (generated by the shadcn CLI). They wrap
    // Radix/recharts whose payload types are `any`, so the app-level type-aware
    // strictness produces unavoidable noise here. Keep correctness rules; relax
    // the `any`-propagation rules for this directory only.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      // The vendored skeleton primitive picks a random width during render.
      "react-hooks/purity": "off",
    },
  },
);
